---
# - name: Deploy IC-Webapp Stack
#   hosts: prod
#   become: true

#   roles:
#     - role: odoo_role
#     - role: pgadmin_role
#     - role: ic_webapp_role

- name: Deploy IC-Webapp Stack
  hosts: prod
  become: true

  vars:
    ic_webapp_image: "${IC_WEBAPP_IMAGE}"
    ic_webapp_version: "${VERSION}"
    odoo_port: 8069
    pgadmin_port: 5050
    ic_webapp_port: 8080

  roles:
    - role: odoo_role
    - role: pgadmin_role
    - role: ic_webapp_role
      vars:
        container_name: "ic-webapp"
        app_image: "{{ ic_webapp_image }}:{{ ic_webapp_version }}"
        app_port: "{{ ic_webapp_port }}"

...