apiVersion: v1
kind: Secret
metadata:
  name: odoo-secrets
  namespace: icgroup
  labels:
    env: prod
type: Opaque
stringData:
  POSTGRES_USER: odoo
  POSTGRES_PASSWORD: odoo_secure_password
  POSTGRES_DB: odoo
  PGADMIN_DEFAULT_EMAIL: admin@example.com
  PGADMIN_DEFAULT_PASSWORD: admin_secure_password