apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: icgroup

labels:
  - pairs:
      env: prod
    includeSelectors: false

resources:
  - namespace.yml
  - secrets/secrets.yml
  - configMap/pgadmin-servers-config.yml
  - configMap/ic-webapp-config.yml
  - volumes/postgres-pv-pvc.yml
  - ingress/ingress.yml
  - loadbalancer/metallb-config.yml
  - deployments/postgres-deployment.yml
  - deployments/odoo-deployment.yml
  - deployments/pgadmin-deployment.yml
  - deployments/ic-webapp-deployment.yml
  - services/postgres-service.yml
  - services/odoo-service.yml
  - services/pgadmin-service.yml
  - services/ic-webapp-service.yml
