apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-webapp
  namespace: icgroup
  labels:
    app: ic-webapp
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ic-webapp
      env: prod
  template:
    metadata:
      labels:
        app: ic-webapp
        env: prod
    spec:
      containers:
        - name: ic-webapp
          image: kevinlagaza/ic-webapp:1.0
          ports:
            - containerPort: 8080
          env:
            - name: ODOO_URL
              valueFrom:
                configMapKeyRef:
                  name: ic-webapp-config
                  key: ODOO_URL
            - name: PGADMIN_URL
              valueFrom:
                configMapKeyRef:
                  name: ic-webapp-config
                  key: PGADMIN_URL
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          startupProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            failureThreshold: 3