apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-servers-config
  namespace: icgroup
  labels:
    env: prod
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "Odoo PostgreSQL",
          "Group": "Servers",
          "Host": "postgres-service",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "odoo",
          "ConnectionParameters": {
            "sslmode": "prefer",
            "connect_timeout": 10
          }
          "PassFile": "/pgadmin4/pgpass"
        }
      }
    }
  pgpass: |
    postgres-service:5432:postgres:odoo:odoo_secure_password